### PR TITLE
Add deployment setup targets

### PR DESCRIPTION
**Pull request by 0505gonzalez**

### CODE REVIEW

**Comment by 0505gonzalez** [comment]
@afik please review

**Comment by afik** [comment]
Should we add .idea to gitignore? @0505gonzalez

**Comment by 0505gonzalez** [comment]
I don't think we should gitignore all of it. I checked online and they just suggest that we ignore the iml files and the workspace.xml, which is already done.

**Comment by afik** [comment]
I see.. LGTM

**Pull request merged**
